name: Build 3GX Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup devkitPro
        uses: devkitpro/action@v1
      - name: Build
        run: |
          make
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: "*.3gx"
          
